server:
  port: 8081

spring:
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: 1
      initialization-mode: always

  jpa:
    show-sql: true
    generate-ddl: true
logging:
  config: classpath:log4j2.xml
